{
 "title": "WebSphere Application Server PMI Metrics Dashboard",
 "description": "Visualize PMI metrics data for your WebSphere Application Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "process_cpu_utilization" } },
   { "name": "node", "query": { "query": "process_cpu_utilization" } },
   { "name": "server", "label": "server", "query": { "query": "process_cpu_utilization" } },
   { "name": "appname", "label": "appname", "query": { "query": "was_servlet_requests_total" } },
   {
    "name": "dur",
    "label": "Duration Range",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   {
    "name": "maxHeapUsageProjection",
    "label": "Max Heap Usage Projection (hours)",
    "query": "1"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "description": "Displays the \"recent CPU usage\" for the Java Virtual Machine processes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_utilization{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
     "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "description": "The average CPU utilization since the last query. The System CPU load metric value is only available from the nodeagent server from each node.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_utilization{instance=~\"[[instance]]\", node=~\"[[node]]\"}",
     "legendFormat": "instance: {{instance}}, node: {{node}}"
    }
   ]
  },
  { "title": "Memory Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Heap Usage (Percentage)",
   "type": "graph",
   "description": "Shows the Heap Usage in graph format.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"} / jvm_memory_max_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"} ",
     "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Heap Usage (Percentage)",
   "type": "table",
   "description": "Shows the Heap Usage in graph format in table format.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"} / jvm_memory_max_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"} "
    }
   ]
  },
  {
   "title": "Heap Usage (Bytes)",
   "type": "graph",
   "description": "The current Heap used by the jvms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
     "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
    }
   ]
  },
  {
   "title": "Heap Usage (Bytes)",
   "type": "table",
   "description": "Shows the Heap Usage in table format.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}"
    }
   ]
  },
  {
   "title": "Increasing Heap Usage Trend Based on Last ${dur}",
   "type": "table",
   "description": "Instances with an increase in heap usage within the last ${dur}.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "deriv(jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}${dur}) > 0"
    }
   ]
  },
  {
   "title": "Servers That May Reach Max Heap Usage Within [$maxHeapUsageProjection hour(s)] Based on Last [[dur]]",
   "type": "table",
   "description": "Instances projected to reach the max heap size within [$maxHeapUsageProjection hour(s)] based on  data over the last [[dur]].",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "predict_linear(jvm_memory_used_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]], $maxHeapUsageProjection * 3600) >  jvm_memory_max_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}"
    }
   ]
  },
  {
   "title": "Maximum Heap Size",
   "type": "table",
   "description": "An instance's maximum heap size. This value is based on the Xmx value set on admin console for the JVM.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}"
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest Servlets Over Last [[dur]] by Average Response Time",
     "type": "table",
     "description": "The average response time for requests made to a particular servlet based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(rate(was_servlet_response_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]]) / rate(was_servlet_requests_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])) by (servlet, instance, appname) > 0"
      }
     ]
    },
    {
     "title": "Servlet Request Count Over Last [[dur]]",
     "type": "graph",
     "description": "The number of visits made to a servlet instance within the past [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(was_servlet_requests_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])) by (servlet, instance, node, server, appname)",
       "legendFormat": "servlet: {{servlet}}, node: {{node}}, server {{server}}, appname: {{appname}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Servlet Request Over Last [[dur]]",
     "type": "graph",
     "description": "The average response time for a request made to a servlet based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(was_servlet_response_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]]) / rate(was_servlet_requests_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]]) ",
       "legendFormat": "servlet: {{servlet}}, node: {{node}}, server {{server}}, appname: {{appname}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Request Count by Servlet Over Last [[dur]]",
     "type": "graph",
     "description": "The sum of visits to a particular servlet over all servers across nodes and instances based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(was_servlet_requests_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])) by (servlet, appname)",
       "legendFormat": "servlet: {{servlet}}, appname: {{appname}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] By Servlet",
     "type": "graph",
     "description": "The average response time for requests made to a particular servlet, across all servers nodes and instances based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(was_servlet_response_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]]) / rate(was_servlet_requests_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])) by (servlet, appname)",
       "legendFormat": "servlet: {{servlet}}, appname: {{appname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EJBs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Time per EJB Over Last [[dur]]",
     "type": "graph",
     "description": "The average response time for an EJB based on data over the last [[dur]].",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(was_ejb_response_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) / rate(was_ejb_responses_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])) by (ejb, instance)",
       "legendFormat": "instance: {{instance}}, ejb: {{ejb}}"
      }
     ]
    },
    {
     "title": "Slowest EJBs Over Last [[dur]] by Average Response Time",
     "type": "table",
     "description": "Table that lists the slowest EJBs over the last [[dur]].",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "avg(rate(was_ejb_response_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) / rate(was_ejb_responses_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])) by (instance, ejb) > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Used Over Last [[dur]]",
     "type": "table",
     "description": "The total number of connection requests that were used over the last [[dur]]. Any connections that are currently in use are not included in this total.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "increase(was_connectionpool_inUse_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Connection Requests Queued Over Last [[dur]]",
     "type": "table",
     "description": "The total number of connection requests that waited for a connection because of a full connection pool over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "increase(was_connectionpool_wait_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Average Time Usage per Connection Over Last ${dur}",
     "type": "graph",
     "description": "The average time any used connection was put in use, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(was_connectionpool_inUse_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}${dur}) / rate(was_connectionpool_inUse_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}${dur}) > 0",
       "legendFormat": "instance: {{instance}},  jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Average Wait Time per Queued Connection Request Over Last ${dur}",
     "type": "graph",
     "description": "The average wait time for any queued connection request, based on data over the last ${dur}.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(was_connectionpool_wait_time_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) / rate(was_connectionpool_wait_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) > 0",
       "legendFormat": "instance: {{instance}},  jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "description": "The sum of managed connections in the free, shared, and unshared pools.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_connectionpool_managed_connections{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "instance: {{instance}}, jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "description": "The number of free connections in the pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_connectionpool_free_connections{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "instance: {{instance}}, jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "description": "The number of connections that are in use. ",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_connectionpool_connectionHandles{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "instance: {{instance}}, jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Connections created in the past [[dur]]",
     "type": "graph",
     "description": "The total number of managed connections created in the past [[dur]]",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_connectionpool_create_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, jndiname: {{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Connections Destroyed in the past [[dur]]",
     "type": "graph",
     "description": "The total number of managed connections destroyed since the pool was created.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_connectionpool_close_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, jndiname={{jndiname}}, node: {{node}}, server: {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SIB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Data (in bytes) Written in the past [[dur]] from the Messaging Engines ",
     "type": "graph",
     "description": "The total amount of message data (in bytes) written in the past [[dur]] from the messaging engines.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_sib_communication_me_messageWrite_bytes_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Message Data (in bytes) Read in the past [[dur]] from the Message Engines ",
     "type": "graph",
     "description": "The total amount of message data (in bytes) read in the past [[dur]] from the messaging engines.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_sib_communication_me_messageRead_bytes_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Message Data (in bytes) Written in the past [[dur]] from the Clients",
     "type": "graph",
     "description": "The total amount of message data (in bytes) written in the past [[dur]] from the Clients",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_sib_communication_client_messageWrite_bytes_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Message Data (in bytes) Read in the past [[dur]] from the Clients",
     "type": "graph",
     "description": "The total amount of message data (in bytes) read in the past [[dur]] from the Clients",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_sib_communication_client_messageRead_bytes_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Messages Produced by Queue in the last [[dur]]",
     "type": "graph",
     "description": "Messages Produced by Queue in the last [[dur]]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(was_sib_queue_messageProduced_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])) by (queue)",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}, queue: {{queue}}"
      }
     ]
    },
    {
     "title": "Messages Consumed by Queue in the last [[dur]]",
     "type": "graph",
     "description": "Messages Consumed by Queue in the last [[dur]]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(was_sib_queue_messageConsumed_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])) by (queue)",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}, queue: {{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "A session is considered active if the application server is processing a request that uses that user session.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_session_active_sessions{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}",
       "legendFormat": "instance: {{instance}}, appname: {{appname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Live  Sessions",
     "type": "graph",
     "description": "A session is considered live if the session is loaded into memory by the application server.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_session_live_sessions{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}",
       "legendFormat": "instance: {{instance}}, appname: {{appname}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Invalidated Sessions in the past [[dur]]",
     "type": "graph",
     "description": "The number of sessions that were invalidated.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_session_invalidated_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, appname: {{appname}}"
      }
     ]
    },
    {
     "title": "Created Sessions in the past [[dur]]",
     "type": "graph",
     "description": "Created sessions in the last [[dur]]",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_session_create_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\", appname=~\"[[appname]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, appname: {{appname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Largest Thread Pool Sizes Over Last [[dur]]",
     "type": "table",
     "description": "The size of the thread pools in each server, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "max_over_time(was_threadpool_size{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_threadpool_active_threads{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "pool: {{pool}}, instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Thread Pool Size",
     "type": "graph",
     "description": "The size of the thread pool in each server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_threadpool_size{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "instance: {{instance}}, pool: {{pool}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Declared Hung Threads in the past [[dur]]",
     "type": "graph",
     "description": "The number of threads declared hung in the last [[dur]]",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(was_threadpool_declaredThreadHungs_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, pool: {{pool}}, node: {{node}}, server: {{server}}"
      }
     ]
    },
    {
     "title": "Concurrent Hung Threads",
     "type": "graph",
     "description": "The number of concurrent hung threads",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "was_threadpool_concurrentHung_threads{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}",
       "legendFormat": "instance: {{instance}}, pool: {{pool}}, node: {{node}}, server: {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent Garbage Collecting During Last [[dur]]",
     "type": "table",
     "description": "A table reporting the portion of time a specific server has spent Garbage Collecting in the last [[dur]].",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(jvm_gc_duration_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle [[dur]] moving average",
     "type": "graph",
     "description": "The average time a server took on garbage collection, based on data over the last [[dur]].",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_duration_seconds_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]]) / rate(jvm_gc_total{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}[[dur]])",
       "legendFormat": "instance: {{instance}}, node: {{node}}, server: {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table",
     "description": "The time elapsed since the start of the JVM.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "process_uptime_seconds{instance=~\"[[instance]]\", node=~\"[[node]]\", server=~\"[[server]]\"}"
      }
     ]
    }
   ]
  }
 ]
}